APP_TITLE = "FinPilot-FinancialAI — Equity Research Dashboard"
APP_ICON = "📈"
APP_VERSION = "1.0.0"

DEFAULT_TICKER = "AAPL"
DEFAULT_PERIOD = "2y"
DEFAULT_NEWS_COUNT = 15
DEFAULT_GROQ_MODEL = "llama-3.3-70b-versatile"

GROQ_MODELS = [
    "llama-3.3-70b-versatile",
    "llama-3.1-8b-instant",
    "mixtral-8x7b-32768",
]

PERIODS = {
    "6 Months": "6mo",
    "1 Year": "1y",
    "2 Years": "2y",
    "3 Years": "3y",
    "5 Years": "5y",
}

COLORS = {
    "positive": "#1D9E75",
    "negative": "#D85A30",
    "neutral": "#888780",
    "buy": "#1D9E75",
    "hold": "#BA7517",
    "sell": "#D85A30",
    "primary": "#185FA5",
    "bg": "#FAFAF8",
    "card": "#FFFFFF",
    "border": "#E8E6E0",
    "text": "#2C2C2A",
    "muted": "#888780",
}

RISK_DISCLAIMER = (
    "This dashboard has been generated by an automated AI system using publicly "
    "available financial data (Yahoo Finance) processed by Groq Llama-3. It is "
    "provided for informational and educational purposes only and does NOT constitute "
    "investment advice. Always consult a qualified financial adviser before making "
    "investment decisions. The authors accept no liability for financial losses."
)
